headers:
  x-sort:
    displayName: Sorting.
    description: |
      - Header to configure the sort of a resource. Format `field<space>field...`
      - A `-` indicates a reverse order for the column
    type: string
    example: |
      "firstname -lastname"
